### ISSUE TITLE
Failed to fetch current robot state

### ISSUE THREAD

**Issue by Diankuang-Wu** [Steigner/ROS_UR3_control#1]
Hi, I copy the codes, and input the command:
1] roslaunch ur_gazebo ur3.launch limited:=true
2] roslaunch ur3_moveit_config ur3_moveit_planning_execution.launch sim:=true limited:=true
3] rosrun testos s_traj.py
also,
1] roslaunch testos rl.launch
2] roslaunch ur3_moveit_planning.launch
3] rosrun testos s_traj.py
face a same issue:

=========>>> PRESS 'ENTER' CONFIGURATION
[ INFO] [1596791045.980253708]: Loading robot model 'ur3'...
[ WARN] [1596791045.980837610]: Skipping virtual joint 'fixed_base' because its child frame 'base_link' does not match the URDF frame 'world'
[ INFO] [1596791045.980859451]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ WARN] [1596791046.052541693, 1309.635000000]: Kinematics solver doesn't support #attempts anymore, but only a timeout.
Please remove the parameter '/robot_description_kinematics/manipulator/kinematics_solver_attempts' from your configuration.
[ INFO] [1596791047.245663905, 1310.828000000]: Ready to take commands for planning group manipulator.
[ INFO] [1596791050.757244805, 1314.332000000]: Didn't received robot state (joint angles) with recent timestamp within 1 seconds.
Check clock synchronization if your are running ROS across multiple machines!
**[ERROR] [1596791050.757294649, 1314.332000000]: Failed to fetch current robot state**
Traceback (most recent call last):
  File "/home/wu/catkin_ws/src/ROS_UR3_control/testos/src/s_traj.py", line 254, in <module>
    main()
  File "/home/wu/catkin_ws/src/ROS_UR3_control/testos/src/s_traj.py", line 205, in main
    tar_sim.init_motion()
  File "/home/wu/catkin_ws/src/ROS_UR3_control/testos/src/s_traj.py", line 56, in init_motion
    joint_goal[0] = -pi/2
**IndexError: list assignment index out of range**

after several tries and google, the issue wasn't  solved, could you give some advice? Thank you

**Comment by Steigner** [comment]
Hi, I suppose problem is in **get_current_joint_values()**. Please check out this issue https://github.com/ros-planning/moveit/issues/1187, i think there you'll be able to find out solve in answer **Hubert51**. 
During testing this script, I never had this issue in method **init_motion()**, so maybe try to check out, if you have install all **moveit** depedencies. So hopefully it will help you!

**Comment by Diankuang-Wu** [comment]
Thank you, I have figured out the issue, the reason of it should be a compiling error about ur_modern_driver when catkin_make it. It should be avoided,but I am careless.
But now, when I input the commands:
1] roslaunch testos rl.launch
2] roslaunch ur3_moveit_planning.launch
3] rosrun testos run_Q.py (or: rosrun testos run_DQN.py)
I face a new issue:
/home/wu/图片/2020-08-10 18-33-30屏幕截图.png
how should I do for it? Thank you

**Comment by Diankuang-Wu** [comment]
Thank you, I have figured out the issue, the reason of it should be a compiling error about ur_modern_driver when catkin_make it. It should be avoided,but I am careless.
But now, when I input the commands:
1] roslaunch testos rl.launch
2] roslaunch ur3_moveit_planning.launch
3] rosrun testos run_Q.py (or: rosrun testos run_DQN.py)
I face a new issue:
1] Gym environment done
2] Start episode:0
3] Simulation reset
**4] ERROR: Can't reset the simulation!
5] ERROR: Can't reset the simulation!
6] ERROR: Can't reset the simulation!**
...

how should I do for it? Thank you
